version: '3.9'
services:

   backend:
      build:
        context: ./
        dockerfile: Dockerfile
        target: development
      container_name: backend
      restart: always
      env_file:
        - .env
      volumes:
       - .:/usr/src/app
      ports:
        - '3000:3000'
      depends_on:
        migratedb:
            condition: service_completed_successfully
        database:
            condition: service_started
   database:
      image: postgres
      restart: always
      container_name: db
      environment:
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}
      volumes:
         -  db-data:/var/lib/postgresql
      ports:
       - "${DB_PORT}:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
        # intervalDB_PASS: 10s
        timeout: 5s
        retries: 5
      expose:
      - 5434
     
   migratedb:
        build:
          context: ./
          dockerfile: Dockerfile
          target: development
        restart: no
        environment:
            - DATABASE_URL=${DATABASE_URL}
        command:
            [
                "./wait-for-it/wait-for-it.sh",
                "database:5432",
                "--",
                "npx",
                "prisma",
                "migrate",
                "deploy",
            ]
  
        depends_on:
            database:
                condition: service_started
          
   rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - "5672:5672"  # RabbitMQ main port
        - "15672:15672"  # RabbitMQ management plugin port
      environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_log:/var/log/rabbitmq
       

volumes:
      db-data:
      rabbitmq_data:
      rabbitmq_log:

      

  